version: '3'
services:  
  db:
    image: postgres:14
    volumes:
      - ./data-1:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB

  pgbouncer:
    image: edoburu/pgbouncer
    environment:
       - DB_USER=$POSTGRES_USER
       - DB_PASSWORD=$POSTGRES_PASSWORD
       - DB_HOST=$POSTGRES_DB_HOST
       - DB_NAME=$POSTGRES_DB
       - POOL_MODE=transaction
       - ADMIN_USERS=postgres,dbuser
    ports:
      - "5432:5432"
    depends_on:
      - db
